version: '3.1'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: template_db
      MYSQL_USER: template
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  spring-app:
    build:
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    restart: unless-stopped