spring:
  application:
    name: Template API
  datasource:
    url: ${DB_URL:jdbc:mysql://db:3306/template_db}
    username: ${DB_USER:template}
    password: ${DB_PASSWORD:password}
    driver: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: none

server:
  port: 9000

flyway:
  baselineOnMigrate: true

hibernate:
  show_sql: true